// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMarketplaceListing(arg1:string):Promise<main.Root>;

export function GetOllamaModels():Promise<Array<main.Model>>;
