// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMarketplaceListing(arg1) {
  return window['go']['main']['App']['GetMarketplaceListing'](arg1);
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function PostOllamaModel(arg1, arg2) {
  return window['go']['main']['App']['PostOllamaModel'](arg1, arg2);
}
